### ISSUE TITLE
Some videos cannot be launched from the page

### ISSUE THREAD

**Issue by floriankdrone** [MisterAlex95/youtube-downloader-front#1]
I will add screenshots later

**Comment by floriankdrone** [comment]
<img width="1037" alt="Screen Shot 2020-01-28 at 21 59 41" src="https://user-images.githubusercontent.com/10310339/73304965-88811d00-4219-11ea-852e-c67a1908e01b.png">

**Comment by MisterAlex95** [comment]
That means the user who uploaded this video doesn't authorize the embeded :(
