### ISSUE TITLE
Tags could be pre-determined according to the video information

### ISSUE THREAD

**Issue by floriankdrone** [MisterAlex95/youtube-downloader-front#2]
based on these tags:

<img width="920" alt="Capture d’écran 2020-01-28 à 13 56 45" src="https://user-images.githubusercontent.com/10310339/73265853-07ecfd00-41d6-11ea-81b7-89c84a1e39b4.png">

**Comment by MisterAlex95** [comment]
We don't have access to these informations using the youtube api :( 
sorry
